id: P44152274
initial_creation_type: input
source_metadata:
  title: Pema Kunzang Rangdrol
  language: bo
  description: 'Texts by and about Muksang Tulku Pema Kunzang Rangdrol (Padma kun
    bzang rang grol, 1916–1984) of the Palyul tradition:'
  volume:
    a1af2dd72443451ba56ebc3f9929452d:
      title: Brief Biography of Kharlek Tulku Pema Kunzang Rangdrol
      parent: Biography
    13cc34cfb8a44c8492a83bf6549d6a83:
      title: Annotation Commentary on the Special Teaching of the Wise and Glorious
        King
      parent: Dzogchen
created_at: '2022-03-01T01:16:02.154287'
last_modified_at: '2022-03-01T01:16:02.154290'
